Repository Reading-Front/react-design-pattern, pull requests merged in 2025-09, with the labels that each got.

#49 [4장] 리액트 컴포넌트 설계하기 - 박동현
  4장-리액트 컴포넌트 설계하기/박동현.md
Labels: 4장 리액트 컴포넌트 설계하기

#55 [5장] 리액트 테스팅 기법 - 박동현
  5장-리액트 테스팅/박동현.md
Labels: 5장 리액트 테스팅

#46 [4장] 리액트 컴포넌트 설계하기 - 박선화
  4장-리액트 컴포넌트 설계하기/박선화.md
Labels: 4장 리액트 컴포넌트 설계하기

#58 [7장] 리액트에서의 테스트 주도 개발 - 박선화
  7장-리액트에서의 테스트 주도 개발/박선화.md
Labels: 7장 리액트에서의 테스트 주도 개발

#50 [5장] 테스팅 기법 - 박진수
  5장-리액트 테스팅/박진수.md
Labels: 5장 리액트 테스팅

#56 [6장] 일반적인 리팩터링 기법 살펴보기 - 박진수
  6장-일반적인 리팩터링 기법 살펴보기/박진수.md
Labels: 6장 일반적인 리팩터링 기법 살펴보기

#60 [7장] 테스팅 기법 - 박동현
  6장-일반적인 리팩터링 기법 살펴보기/박동현.md
  7장-리액트에서의 테스트 주도 개발/박동현.md
Labels: 7장 리액트에서의 테스트 주도 개발

#61 [8장] 리액트 데이터 관리 - 박선화
  8장-리액트 데이터 관리/박선화.md
Labels: 8장 리액트 데이터 관리

#62 [9장] 리액트 설계 원칙 적용 - 박선화
  9장-리액트 설계 원칙 적용/박선화.md
Labels: 9장 리액트 설계 원칙 적용

#63 [10장] 합성 패턴 - 박선화
  10장-합성 패턴/박선화.md
Labels: 10장 합성 패턴

#65 [8장] 리액트 데이터 관리 - 박보라
  8장-리액트 데이터 관리/박보라.md
Labels: 8장 리액트 데이터 관리
